### ISSUE TITLE
Invalid SSL certificate: Error code 526 (2023-11-06)

### ISSUE THREAD

**Issue by yawnoc** [oris-tool/oris-tool.github.io#4]
Whether visiting <https://oris-tool.github.io/> or <https://www.oris-tool.org/>, I get " Invalid SSL certificate: Error code 526":

![Screenshot of invalid SSL certificate message.](https://github.com/oris-tool/oris-tool.github.io/assets/48375680/b94167a5-b220-452c-ab49-b2f04f0a3bf2)

**Comment by paolieri** [comment]
Should be resolved
